### ISSUE TITLE
Get working!

### ISSUE THREAD

**Issue by m0nk** [jlegs/blackjack#1]
An empty repo? no code :( get on it man!

**Comment by righteousrenegade** [comment]
Haha! I'll do that!! Not sure if I'll do it as a Django app or just a command line game. Probably Django app, since it's easier/quicker to do. Although an executable might not be bad either. I guess i'd have to make it work for various OS'es though, which doesn't exactly thrill me.

**Comment by m0nk** [comment]
I see some code :) (sorry I didn't reply back) good looking man
